[package]
name = "sabi_playground"
version = "0.1.0"
authors = ["rodrimati1992 <rodrimatt1985@gmail.com>"]
edition = "2021"

[dependencies]
abi_stable={version="*",path="../abi_stable"}
core_extensions={ version = "1.5.2", default_features = false, features = ["std"] }
